name: xempi
description: "A simple plugin to manage XMPP connections based on pure XML Documents"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web_socket_channel: ^3.0.0
  xml: ^6.5.0
  universal_io: ^2.2.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ferativ.xempi
        pluginClass: XempiPlugin
      ios:
        pluginClass: XempiPlugin
      linux:
        pluginClass: XempiPlugin
      macos:
        pluginClass: XempiPlugin
      windows:
        pluginClass: XempiPluginCApi
